JWT:
  SECRET_KEY: x12rNNe_S4Rw0WtzQ1Ec2z5JQNAHlkiG86NLOsY6ECRVtSADc=
  TOKEN_EXPIRE: 365d 

API:
  HOST: localhost
  PORT: 8081
  ALLOW_ORIGINS:
    - http://localhost:4200
    - http://localhost:4202
    - http://localhost:8080
    - http://localhost:8081

DB_DSN: host:password@tcp(localhost:3306)/dbname